GET http://localhost:5087/games
###
GET http://localhost:5087/games/2
###
POST http://localhost:5087/games
Content-Type: application/json

{
    "name": "God of War",
    "genreId": 2,
    "price": 59.99,
    "releaseDate": "2017-08-15"
}

###
PUT http://localhost:5087/games/3
Content-Type: application/json

{
    "name": "Contra Rogue Corps",
    "genreId": 1,
    "price": 59.99,
    "releaseDate": "2017-03-05"
}

###
DELETE http://localhost:5087/games/3

###
GET http://localhost:5087/genres